## NumPy - Numeric Python
    Create Muti dimensional arrays
    Perform Numeric Computations on data

In [1]:
import numpy as np

In [2]:
empids=[101,102,103]

In [3]:
type(empids)

list

In [4]:
arr1=np.array([101,102,103])
arr1

array([101, 102, 103])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(3,)

In [7]:
arr2=np.array([[1,2],[2,3]])
arr2

array([[1, 2],
       [2, 3]])

In [8]:
arr2.shape

(2, 2)

In [9]:

arr4 = np.array([[1,2,3],[2]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [10]:
arr4 = np.array([[1,2,3],[2,0,0]])

In [11]:
arr4

array([[1, 2, 3],
       [2, 0, 0]])

In [12]:
arr3=np.array([[[1,3,4],[2,3,4]]])

In [13]:
arr3

array([[[1, 3, 4],
        [2, 3, 4]]])

In [14]:
arr3.shape

(1, 2, 3)

In [15]:
arr1

array([101, 102, 103])

In [17]:
arr1[0]

np.int64(101)

In [19]:
arr1[1]

np.int64(102)

In [20]:
arr2

array([[1, 2],
       [2, 3]])

In [21]:
arr2.shape

(2, 2)

In [22]:
arr2[0,0]

np.int64(1)

In [23]:
arr2[0,1]

np.int64(2)

In [24]:
arr2[1,0]

np.int64(2)

In [25]:
arr2[1,1]

np.int64(3)

In [26]:
arr3

array([[[1, 3, 4],
        [2, 3, 4]]])

In [27]:
arr3.shape

(1, 2, 3)

In [28]:
arr3[0,0,0]

np.int64(1)

In [29]:
arr3[0,0,1]

np.int64(3)

In [31]:
arr3[0,0,2]

np.int64(4)

In [32]:
arr3[0,1]

array([2, 3, 4])

In [33]:
arr3[0,1,0]

np.int64(2)

In [34]:
arr3[0,1,1]

np.int64(3)

In [35]:
arr3[0,1,2]

np.int64(4)

In [37]:
np.zeros((1,2))

array([[0., 0.]])

In [39]:
np.zeros((1))

array([0.])

In [41]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [42]:
np.zeros((4))

array([0., 0., 0., 0.])

In [43]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [45]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [46]:
range(1,10)

range(1, 10)

In [47]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [48]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [49]:
tuple(range(1,10,2))

(1, 3, 5, 7, 9)

In [50]:
np.arange(25,100)

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
       76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
       93, 94, 95, 96, 97, 98, 99])

In [51]:
np.arange(25,100,2)

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57,
       59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91,
       93, 95, 97, 99])

In [53]:
params=np.arange(25,100,2)
params

array([25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57,
       59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91,
       93, 95, 97, 99])

In [54]:
type(params)

numpy.ndarray

In [55]:
np.sum(arr1)

np.int64(306)

In [56]:
np.max(arr1)

np.int64(103)

In [57]:
np.min(arr2)

np.int64(1)

In [58]:
empids

[101, 102, 103]

In [59]:
empids*3

[101, 102, 103, 101, 102, 103, 101, 102, 103]

In [60]:
new_data=[]
for i in empids:
    new_data.append(i*3)
print(new_data)

[303, 306, 309]


In [61]:
arr1*3

array([303, 306, 309])

In [62]:

np.mean(arr1)

np.float64(102.0)

### absolute value
    -1 -3 -50
    |-1| = 1
    |-3| = 3
    |-50| = 50

In [64]:
arrnew=np.array([-3,-45,-50])

In [65]:
np.absolute(arrnew)

array([ 3, 45, 50])

In [66]:
np.max(arr1)

np.int64(103)

In [67]:
# position of max element present in arr1
np.argmax(arr1)

np.int64(2)

In [68]:
arr2

array([[1, 2],
       [2, 3]])

In [69]:
np.argmin(arr2)

np.int64(0)

In [70]:
np.random.random(45)

array([0.94065293, 0.3057731 , 0.21671191, 0.05053104, 0.47785859,
       0.31725496, 0.91630106, 0.81979224, 0.27632057, 0.51809156,
       0.96868895, 0.5712126 , 0.06251473, 0.59917635, 0.95427437,
       0.23163906, 0.53456138, 0.54870699, 0.25932092, 0.14826765,
       0.54163254, 0.39439295, 0.47425121, 0.66823151, 0.2079899 ,
       0.75277552, 0.46438397, 0.80208236, 0.16108211, 0.81300585,
       0.12812158, 0.11889554, 0.98308979, 0.4738833 , 0.91821115,
       0.5692421 , 0.38817425, 0.3612805 , 0.71739048, 0.53318425,
       0.38033256, 0.34925795, 0.42927845, 0.89941006, 0.05304978])

In [78]:
np.random.randint(100,1000,45)

array([696, 417, 913, 652, 985, 146, 506, 537, 646, 897, 128, 247, 279,
       383, 403, 907, 689, 589, 813, 237, 129, 627, 820, 932, 125, 594,
       924, 979, 293, 600, 478, 609, 620, 814, 544, 590, 708, 401, 419,
       679, 881, 975, 643, 974, 183], dtype=int32)

In [79]:
normal_data=np.random.normal(size=50)

In [73]:
import seaborn as sns

In [80]:
sns.histplot(normal_data,kde=True)

<Axes: ylabel='Count'>

In [81]:
np.mean(normal_data)

np.float64(-0.1737823284911937)

In [82]:
np.median(normal_data)

np.float64(-0.09091718647116727)

In [83]:
np.sqrt(25)

np.float64(5.0)

In [84]:
np.sqrt(121)

np.float64(11.0)

In [85]:
np.sin(arr1)

array([0.45202579, 0.99482679, 0.62298863])

In [86]:

np.cos(arr1)

array([ 0.89200487,  0.1015857 , -0.78223089])

In [87]:
np.tan(arr1)

array([ 0.5067526 ,  9.79298026, -0.7964255 ])